## NOTE: to retain configuration; mount a Docker volume, or use a bind-mount, on /var/lib/zerotier-one

FROM registry.access.redhat.com/ubi8/ubi:latest as builder

## Supports x86_64, x86, arm, and arm64

ADD container_root /

RUN rpm --import /opt/zt-gpg-key && \
    dnf update -y && \
    dnf install -y \
        curl \
        gnupg \
        zerotier-one && \
    dnf clean all

FROM registry.access.redhat.com/ubi8/ubi:latest
LABEL description="Containerized ZeroTier One for use on CoreOS or other container-only Linux hosts."

# ZeroTier relies on UDP port 9993
EXPOSE 9993/udp

RUN mkdir -p /var/lib/zerotier-one
COPY --from=builder /usr/sbin/zerotier-cli /usr/sbin/zerotier-cli
COPY --from=builder /usr/sbin/zerotier-idtool /usr/sbin/zerotier-idtool
COPY --from=builder /usr/sbin/zerotier-one /usr/sbin/zerotier-one
COPY --from=builder /main.sh /main.sh

ENTRYPOINT ["/main.sh"]
CMD ["zerotier-one"]